version: "3.6"
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "${POSTGRES_LOCAL_PORT}:5432"
    volumes:
      - "db:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: bigscreen

volumes:
  db:
    name: postgres-bigscreen
