api:
  dashboard: true
  insecure: true
providers:
  docker: {}
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
certificatesResolvers:
  default:
    acme:
      dnsChallenge:
        provider: selectel