api:
  dashboard: true
providers:
  docker: {}
  file:
    directory: /traefik-dynamic-conf
    watch: true
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
certificatesResolvers:
  default:
    acme:
      dnsChallenge:
        provider: selectel